Issue 88 - Update iGame.guide file
MrZammler/iGame pull request #112
Opened 2020-09-21 11:35 UTC by walkero-gr

With this PR I updated the iGame.guide, describing all the GUI menu items, windows, tooltypes, and updated all the sections of the document to the latest changes.

Added also a changelog file. The format of this changelog file is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/). Tried to add as much information as I could find for the previous versions.

2020-09-22 21:09 UTC, coldacid requested changes
I found a number of possessives with apostrophes that should be corrected.

2020-09-22 21:09 UTC, coldacid commented on required_files/iGame.guide
> +iGame can "discover" your games on pre-defined repositories and create a small database. You can then categorize each game according to it's genre, provide a small screenshot image to be displayed wh
"it's" should be "its" (without apostrophe) since this use is not a contraction of "it is".

2020-09-22 21:09 UTC, coldacid commented on required_files/iGame.guide
> +iGame saves it's support files on it's own folder (PROGDIR:). We recommend you to install it on it's own separated directory in your hard disk.
These should all be "its".

2020-09-22 21:09 UTC, coldacid commented on required_files/iGame.guide
> +By this window you can set the "Title" of the game/demo, select the path on HD of the executable and set it's "Genre".
"its".

2020-09-22 21:09 UTC, coldacid commented on required_files/iGame.guide
> +The iGame settings window opens from the menu item "Settings > Settings...". This configuration selections override the iGame tooltypes set on it's icon. These are saved on a text file named "igame.p
"its".

2020-09-22 21:09 UTC, coldacid commented on required_files/iGame.guide
> +@{b}TITLESFROMDIRS@{ub} gets the game/demo title from it's parent directory
"its".

2020-09-22 21:12 UTC, coldacid commented
Adding a changelog is a good idea, but it's probably something that should have been added directly into master, or through a separate PR so that this stays focused on the guide file.

2020-09-23 11:03 UTC, walkero-gr commented
@coldacid Thank you so much for taking the time and check this PR. I will do all the proposed changes.

I added the changelog in this PR because I removed this part from the guide. We can add more info on that in the future. I need to check all the commits for the versions I miss on this changelog, and add some detail. Not crucial though for a new release

2020-09-24 21:52 UTC, coldacid approved these changes

2020-09-24 22:19 UTC, merged